title: Klaar & Kees Media
description: Video's voor uw bedrijf met karakter & pit. 
url: https://itsguus.github.io/klaare_en_kees_self/


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"

collections:
  tips: 
    output: true